replicaCount: 1

image:
  repository: subhransu253378/blog-backend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
